apiVersion: apps/v1
kind: Deployment
metadata:
  name: deposit-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deposit-service
  template:
    metadata:
      labels:
        app: deposit-service
    spec:
      containers:
        - name: deposit-service
          image: deposit-service:latest
          ports:
            - containerPort: 1980
            - containerPort: 8090
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector:4317"
---
apiVersion: v1
kind: Service
metadata:
  name: deposit-service
spec:
  selector:
    app: deposit-service
  ports:
    - name: deposit-servicet
      port: 8180
