apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  labels:
    app: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
      - name: loki
        image: grafana/loki:latest
        ports:
        - containerPort: 3100
          name: http-metrics
---

apiVersion: v1
kind: Service
metadata:
  name: loki
  labels:
    app: loki
spec:
  type: LoadBalancer
  ports:
  - port: 3100
    targetPort: http-metrics
  selector:
    app: loki